version: "3.8"
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
    networks:
      - network-backend
  backend:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    # descomentar para usar mongo local
    # ports:
    #   - 27017:27017
    networks: 
     - network-backend
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_HOST_PORT}:${MONGO_EXPRESS_CONTAINER_PORT}"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
