global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: keycloak
    static_configs:
      - targets: ["keycloak:8080"]

  - job_name: grafana
    static_configs:
      - targets: ["grafana:3000"]
  
  - job_name: Frontend-Backend
    static_configs:
      - targets: ["node_exporter:9100"]
  
  - job_name: MongoDB
    static_configs:
      - targets: ["mongo_exporter:9216"]
  
  - job_name: PostgresDB
    static_configs:
      - targets: ["postgres-exporter:9187"]