version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - jenkins_network
  ssh-agent:
    image: jenkins/ssh-agent

volumes:
  jenkins_home:

networks:
  jenkins_network: