pipeline {
    agent any
    
    environment {
        
        GIT_REPO = 'git@github.com:clvsick/TaskVerse-Boilerplate.git'
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Configura la credencial SSH
                    withCredentials([userPassword(credentialsId: 'Jenkins-TaskVerse-Boilerplate', passwordVariable: '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', usernameVariable: 'clvsick')]) {
                        // Clona el repositorio utilizando la credencial SSH
                        sh "git clone -b main ${env.GIT_REPO}"
                    }
                }
            }
        }
        // Otros pasos del pipeline aquí
    }
}
