pipeline {
    agent any

    stages {
        
        stage('Git clone the repository') {
            steps {
                // Clone the repository
                git branch: 'main', url: 'https://github.com/TaskVerse/TaskVerse-Boilerplate.git'
                github = 'https://github.com/TaskVerse/TaskVerse-Boilerplate.git'
                echo "Cloning the repository: ${github}"
            }
        }


        stage('Start Docker Containers') {
            steps {
                // Start the containers
                script {
                    sh 'docker compose up --build -d'
                }
            }
            
        }
    }
}