pipeline {
    agent any

    stages {
        
        stage('Build') {
            steps {
                checkout([$class: 'GitSCM',
                        branches: [[name: '*/master']],
                        userRemoteConfigs: [[url: 'https://github.com/TaskVerse/TaskVerse-Boilerplate']]])
            }
        }


        stage('Start Docker Containers') {
            steps {
                // Start the containers
                script {
                    sh 'docker compose up --build -d'
                }
            }
            
        }
    }
}