name: TaskVerse-Boilerplate CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: TaskVerse - Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

  Deploy-Docker-Compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: TaskVerse - BUILD & UP Docker Compose
        run: |
          docker-compose up --build -d
        working-directory: ./  
        env:
          #=====================FRONT & BACK Environments=====================
          FRONTEND_CONTAINER_PORT: ${FRONTEND_CONTAINER_PORT}
          FRONTEND_HOST_PORT: ${FRONTEND_HOST_PORT}
          BACKEND_CONTAINER_PORT: ${BACKEND_CONTAINER_PORT}
          BACKEND_HOST_PORT: ${BACKEND_HOST_PORT}
          #=====================MONGODB Environments=====================
          MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
          MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
          MONGO_EXPRESS_CONTAINER_PORT: ${MONGO_EXPRESS_CONTAINER_PORT}
          MONGO_EXPRESS_HOST_PORT: ${MONGO_EXPRESS_HOST_PORT}
          #=====================MONGO EXPRESS Environments=====================
          ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
          ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
          ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
          #=====================KEYCLOAK Environments=====================
          KEYCLOAK_HOST_PORT: ${KEYCLOAK_HOST_PORT}
          KEYCLOAK_CONTAINER_PORT: ${KEYCLOAK_CONTAINER_PORT}
          KC_DB: ${KC_DB}
          KC_DB_URL_HOST: ${KC_DB_URL_HOST}
          KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
          KC_DB_USERNAME: ${KC_DB_USERNAME}
          KC_DB_PASSWORD: ${KC_DB_PASSWORD}
          KC_DB_SCHEMA: ${KC_DB_SCHEMA}
          KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
          KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
          #=====================POSTGRES Environments=====================
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_HOST_PORT: ${POSTGRES_HOST_PORT}
          POSTGRES_CONTAINER_PORT: ${POSTGRES_CONTAINER_PORT}
  
