name: TaskVerse-Boilerplate CI/CD Pipeline

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Read Secrets
        run: echo ${{ secrets.GITHUB_TOKEN }}
