name: TaskVerse-Boilerplate CI/CD Pipeline

on:
  workflow_dispatch

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker compose
          uses: docker/setup-buildx-action@v1

        - name: Deploy docker compose
          uses: docker/compose-action@v2
          with:
            build: .
            pull: true
            push: true
            files: ./docker/docker-compose.yml